EXEC = PJ1
CC = g++
CFLAGS = -c -Wall
#
$(EXEC) :IS.o
	$(CC) -o $(EXEC) IS.o
#
IS.o :IS.cpp
	$(CC) $(CFLAGS) IS.cpp
#
#MS.o :MS.h MS.cpp
#	$(CC) $(CFLAGS) MS.cpp
##
#QS.o :QS.h QS.cpp
#	$(CC) $(CFLAGS) QS.cpp